/* QUERY PARA REMOÇÃO DA CHAVE DE ACESSO DE DOCUMENTO */

SELECT @@VERSION AS [VERSÃO],
SYSDATETIME() AS [DATA]

USE [ALTERDATA_ERP]
GO

SELECT CdChaveAcessoNFEletronica, * FROM DBO.Documento
WHERE NrDocumento='17374'
AND DtEmissao='2023-10-31 00:00:00.000'

UPDATE DBO.Documento
SET CdChaveAcessoNFEletronica= NULL 
WHERE IdDocumento='00A0004ZHU'