/* EXPURLGO DE DADOS

EXCLUSÃO E LIMPEZA DE DADOS NA BASE */

USE [ALTERDATA_ERP]
GO

SELECT * FROM [dbo.PedidoDeVenda]

SELECT YEAR(DtEmissao)ANO, COUNT(1)QTDLINHAS
FROM [dbo.PedidoDeVenda] GROUP BY YEAR(DtEmissao)
ORDER BY ANO DESC
GO

DBCC SQLPERF(LOGSPACE) -- LISTA DAS BASES DE DADOS DA INSTÂNCIA --
GO

DBCC LOGINFO
GO

SELECT used_log_space_in_bytes/1024/1024 TAMANHO_MB,* FROM sys.dm_db_log_space_usage -- TAMANHO DO ESPAÇO DO LOG USADO
DA BASE DE DADOS EM MEGABYTES --
GO

/* DELETAR OS DADOS DE FORMA AGRESSIVA, UTIL PARA POUCOS DADOS, MAS GERA PROBLEMAS PARA EXCLUSÃO DE MUITOS DADOS DE
UMA VEZ (PODE BLOQUEAR A UTILIZAÇÃO DA TABELA E ESTOURO DO LOG DE TRANSAÇÃO */

DELETE FROM dbo.PedidoDeVenda WHERE DtEmissao < '2021-01-01 00:00:00.000'

SP_WHOISACTIVE -- VERIFICAR O QUE ESTÁ EM EXECUÇÃO NO MOMENTO --
GP

ALTER DATABASE ALTERDATA_ERP SET RECOVERY SIMPLE -- ALTERA A FORMA DE RECUPERAÇÃO DA BASE DA DADOS PARA SIMPLES E PODER
EFETUAR O BACKUP LOG --

BACKUP LOG ALTERDATA_ERP TO DISK = 'C:\BKP\ALTERDATA_ERP_LOG.TRN' -- BACKUP DE LOG PARA DIMINUIR O LOG TRANSACIONAL EM USO APÓS O DELETE AGRESSIVO --
WITH COMPRESSION
GO

/* DELETE EM BLOCO COM VARIÁVEIS E LOOP */

DECLARE @LINHAS_DELETE INT=1

 WHILE @LINHAS_DELETE > 0
 
BEGIN
 BEGIN TRANSACTION -- INICIAR TRANSAÇÃO --
 DELETE TOP(10000) FROM dbo.PedidoDeVenda
 WHERE DtEmissao < '2022-01-01 00:00:00.000'

  SELECT @LINHAS_DELETE = @@ROWCOUNT

   WAITFOR DELAY '00:00:10'
   COMMIT -- CONFIRMAR TRAMSAÇÃO -- 
 END
GO

/* DELETE EFETUANDO O MODO DE TRANSFERENCIA, TRASNFERINDO OS DADOS CLONANDO A TABELA DE REFERÊNCIA.
1 - PRECISA SER COMBINADO UMA JANELA DE MANUTENÇÃO PARA A AÇÃO, SEM USO DA APLICAÇÃO
2 - O SELECT * INTO, SÓ COPIA A ESTRUTURA DA TABELA MAS NÃO OS OBJETOS: PF, FK, TRIGGER, INDICE */

SELECT YEAR(DtEmissao)ANO, COUNT(1)QTDLINHAS
FROM dbo.PedidoDeVenda GROUP BY YEAR(DtEmissao)
ORDER BY ANO DESC
GO

SELECT COUNT(1) EXCLUIR FROM dbo.PedidoDeVenda WHERE DtEmissao < '2022-01-01 00:00:00.000'

SELECT COUNT(1) MANTER FROM dbo.PedidoDeVenda WHERE DtEmissao >= '2022-01-01 00:00:00.000'

SELECT * INTO dbo.PedidoDeVenda_Nova from dbo.PedidoDeVenda_OLD
WHERE DtEmissao >= '2022-01-01 00:00:00.000'

EXEC SP_RENAME 'dbo.PedidoDeVenda','dbo.PedidoDeVenda_OLD' -- RENOMEAR A TABELA A SER EXCLUÍDA --

EXEC SP_RENAME 'dbo.PedidoDeVenda_Nova','dbo.PedidoDeVenda' -- RENOMEAR A TABELA NOVA PARA O NOME DE TABELA PADRÃO --

SELECT COUNT(1) FROM dbo.PedidoDeVenda

SELECT COUNT(1) FROM dbo.PedidoDeVenda_OLD

DROP TABLE dbo.PedidoDeVenda_OLD -- DELETANDO A TABELA ANTIGA --

/* UTILIZANDO O SCRIPT DA TABELA + INSERTI INTO.

1 - GERAR O SCRIPT DA TABELA COM A SUA ESTRTURA COMPLETA, RENOMEANDO-A E EDITANDO AS CHAVES.*/

INSERT INTO dbo.PedidoDeVenda_Nova SELECT * FROM dbo.PedidoDeVenda WHERE DtEmissao >= '2022-01-01 00:00:00.000' -- INSERIR OS DADOS DA TABELA A SER ELIMINADA, PARA A TABELA NOVA -- 

EXEC SP_RENAME 'dbo.PedidoDeVenda','dbo.PedidoDeVenda_OLD' -- RENOMEAR A TABELA A SER EXCLUÍDA --

EXEC SP_RENAME 'dbo.PedidoDeVenda_Nova','dbo.PedidoDeVenda' -- RENOMEAR A TABELA NOVA PARA O NOME DE TABELA PADRÃO --

TRUNCATE TABLE dbo.PedidoDeVenda_OLD -- TRUNCATE PARA DELETAR SÓ AS LINHAS E MANTER A TABELA COM SUA ESTRUTURA --







