/* IDENTIFICANDO E LOCALIZANDO OBJETOS NA BASE DE DADOS */

USE [ALTERDATA_ERP]
GO

SELECT * FROM SYSCOMMENTS

SELECT * FROM SYSCOMMENTS WHERE TEXT LIKE '%PedidoDeVenda%'

SELECT * FROM SYSCOMMENTS WHERE TEXT LIKE '%VIEW%PedidoDeVenda%'

SELECT OBJECT_NAME(ID) AS [NOME_OBJETO],* FROM SYSCOMMENTS WHERE TEXT LIKE '%w_Carapitanga_ConferenciaAdiantamentos%'

EXEC SP_HELPTEXT vw_Carapitanga_ConferenciaAdiantamentos -- QUERY IDENTADA DO OBJETO --