/* ANEXAR BD NA INSTÂNCIA */

CREATE DATABASE LOCADORA
 ON (FILENAME = 'C:\LOCADORA\LOCADORA_DADOS.mdf'),
 (FILENAME = 'C:\LOCADORA\LOCADORA_LOG.ldf')
FOR ATTACH

/* DESANEXAR BD DA INSTÂNCIA */

EXEC sp_detach_db 'LOCADORA', 'true'