/* CONFERÊNCIA DOS JOBS */

SELECT * FROM MSDB..SYSJOBS -- LISTA TODOS OS JOBS DA INSTÂNCIA. --

SELECT * FROM MSDB..SYSJOBSTEPS -- ETAPAS DOS JOBS. --

SELECT * FROM MSDB..SYSJOBSTEPS WHERE COMMAND LIKE '$$' -- CONSULTAR O JOB POR ETAPAS E COMANDOS.