USE [ALTERDATA_ERP]
GO

-- AJUSTA A QUANTIDADE DE VOLUMES NA ABA TRANSPORTADOR DO PEDIDO DE VENDA --

SELECT * FROM dbo.PedidoDeVenda
WHERE CdChamada='222245'

UPDATE dbo.PedidoDeVenda
SET DsVolumes='20'
WHERE idpedidodevenda='00A000506A'

-- AJUSTA A QUANTIDADE DE VOLUMES NA ABA TRANSPORTADOR DO DOCUMENTO --

SELECT * FROM DBO.Documento
WHERE NrDocumento='135562'

SELECT * FROM DBO.DocumentoTransportador
WHERE IdDocumento='00A0007ATK'

UPDATE DBO.DocumentoTransportador
SET DsVolumes='10'
WHERE IdDocumento='00A0007ATK'