/* QUERY PARA AJUSTE DE PEDIDO DE VENDA NÃO VISIÍVEL NO MÓDULO DE LIBERAÇÃO */

USE [ALTERDATA_ERP]
GO

SELECT * FROM dbo.PedidoDeVenda
WHERE CdChamada='178848'

SELECT * FROM dbo.PedidoDeVendaHistorico
WHERE IdPedidoDeVenda='00A00050F2'

-- PAUSAR A TRIGGER PARA RODAR O UPDATE -- 

UPDATE dbo.PedidoDeVendaHistorico
SET DtHistorico='2023-12-26 00:00:00.000'
where IdPedidoDeVenda='00A00050F2'

SELECT @@VERSION AS [VERSÃO],
SYSDATETIME() AS [DATA]