/* QUERY PARA ALTERAR O NÚMERO DO TÍTULO APAGAR */

USE [ALTERDATA_ERP]
GO

SELECT NrTitulo, * from dbo.APagar
WHERE NrTitulo='223073-2'-- TÍTULO CORRETO --
AND CdEmpresa='16'
GO

UPDATE dbo.APagar
SET NrTitulo = '12230730-2'
WHERE IdApagar= '00A00079BM' -- UTILIZAR O iDAReceber
GO

SELECT @@VERSION AS [VERSÃO],
SYSDATETIME() AS [DATA]