/* QUERY PARA ALTERAR O NÚMERO DO TÍTULO ARECEBER */

USE [ALTERDATA_ERP]
GO

SELECT NrTitulo, * from dbo.AReceber
WHERE NrTitulo='001005-3'-- TÍTULO CORRETO --
AND CdEmpresa='1'
GO

UPDATE dbo.AReceber
SET NrTitulo = '146949-3'
WHERE IdAreceber= '00A00067JL' -- UTILIZAR O iDAReceber
GO

SELECT @@VERSION AS [VERSÃO],
SYSDATETIME() AS [DATA]