/* QUERY PARA ALTERAÇÃO DE DATA DE VENCIMENTO PROGRAMADO DO TÍTULO ARECEBER. */

USE [ALTERDATA_ERP]
GO

SELECT IdAreceber, DtEmissao , DtVencimento, DtVencimentoOriginal, 
* FROM DBO.AReceber
WHERE NrTitulo='118896-3'

--SELECT @@VERSION AS [VERSÃO],
--SYSDATETIME() AS [DATA]

--UPDATE DBO.AReceber
--SET DtVencimento ='2024-09-02 00:00:00.000'
--WHERE IdAreceber='00A00053EB'