/* QUERY LIMPAR O CAMPO DA NUMERAÇÃO DO TÍTULO GERADO NO SISTEMA PARA O BANCO */

USE [ALTERDATA_ERP]
GO

SELECT * FROM dbo.areceber
WHERE NrTitulo IN ('18582-1')
AND CdEmpresa='1'
GO

SELECT NrTituloBanco /*AS [NOSSO NUMERO]*/, * FROM DBO.HistoricoCarteira
WHERE IdAReceber IN ('00A0005HEE')
GO

DELETE FROM DBO.HistoricoCarteira
WHERE IdAReceber IN ('00A0005HEE')
AND NrTituloBanco IS NOT NULL
GO

SELECT @@VERSION AS [VERSÃO],
SYSDATETIME() AS [DATA]
