/* QUERY PARA EFETUAR AJUSTE NO CT-E QUE O TOMADOR É DIFERENTE DA EMPRESA INFORMADA*/

USE [ALTERDATA_ERP]
GO

SELECT * FROM dbo.CTe
WHERE NrCTe='262'
AND CdEmpresa='14'

UPDATE dbo.CTe
SET IdPessoaOutroTomador='00A000020I', CdEnderecoPessoaOutroTomador='01', TpTomador='4'
WHERE IdCTe='8896'
AND NrCTe='262'
AND CdEmpresa='14'