/* QUERY PARA EXCLUSÃO DE ITENS NÃO VINCULADOS A PEDIDOS */

USE [ALTERDATA_ERP]
GO

SELECT * FROM DBO.PEDIDODEVENDAITEM
WHERE IdPedidoDeVenda NOT IN(SELECT IdPedidoDeVenda FROM PedidoDeVenda)

--DELETE DBO.PEDIDODEVENDAITEM
WHERE IdPedidoDeVenda NOT IN(SELECT IdPedidoDeVenda FROM PedidoDeVenda)

SELECT @@VERSION AS [VERSÃO],
SYSDATETIME() AS [DATA]